### ISSUE TITLE
Error: Can't find 'action.yml' or 'Dockerfile'

### ISSUE THREAD

**Issue by chrisblakley** [JCofman/webPagetestAction#2]
This action is a great idea and I can't wait to start using it! I used the example from the readme with my own API key and test URL, but I'm getting this error:

```
##[error]Can't find 'action.yml' or 'Dockerfile' under '/home/runner/work/Actions-Again/Actions-Again'.
```
*(note: "Actions-Again" is my repo name that I'm learning actions with)

Am I doing something wrong? Here is a screenshot for reference if that helps:

![Screen Shot 2019-08-23 at 5 08 01 PM](https://user-images.githubusercontent.com/6349678/63623840-a55d5880-c5c8-11e9-9fa1-adebbfc904a9.png)

**Comment by chrisblakley** [comment]
Ok I was able to figure it out. The examples in the documentation might be a little confusing to those new to Github Actions because the `uses` values are pointed to itself. For most of us, we need to point only a single `uses` to `JCofman/webPagetestAction@master`.

I'd recommend updating the readme to include the following example. This would allow anyone to very easily copy/paste it into a `/.github/workflows/webpagetest.yml` file, create the `WEBPAGETEST_API_KEY` secret, update the `TEST_URL` and it'll work.

```yml
on: push
name: Run Webpagetest
jobs:
  webPageTestActions:
    name: WebPageTestActions
    runs-on: ubuntu-latest
    steps:
      - uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: https://example.com
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
```
